### ISSUE TITLE
♻️ Fully Automate Py2Bin Completion Using GhostDev + Encapsulation-Based Test Strategy

### ISSUE THREAD

**Issue by brupelo** [brupelo/py2bin#2]
**Overview**

We want to fully automate the completion of the `py2bin` repository by configuring and integrating [[GhostDev](https://github.com/ghostdev/ghostdev)](https://github.com/ghostdev/ghostdev) with our existing testing and validation policies.

This will allow us to iterate automatically on feature branches using LLMs—ensuring every commit is valid and inching toward a fully complete, correct codebase.

---

### ✅ Goals

* [ ] Create a `.ghostdev.yml` file aligned with our existing [`[policies.txt](https://chatgpt.com/c/policies.txt)`](./policies.txt)
* [ ] Define prompt templates that respect internal API boundaries
* [ ] Ensure GhostDev adheres to our **encapsulation and testing guidelines**
* [ ] Avoid mocking; use real `llvmlite` workflows in tests
* [ ] Validate automation flow through `just test`, `just coverage`, and `py2bin` batch commands

---

### 📄 Reference Policies

Please refer to [`[policies.txt](https://chatgpt.com/c/policies.txt)`](./policies.txt) for merge conditions:

1. ✅ All tests in `tests/done/` must pass.
2. ✅ At least one test in `tests/doing/` must improve.
3. ✅ All unit tests must pass.
4. ✅ Code coverage must not regress.

---

### 🔐 🛡️ Data Encapsulation and Testing Guidelines

We follow a strict rule: **test only the public interface**. Do not access or test `_internal` methods or attributes directly.

🔁 Internal logic should be factored into public helpers if test coverage requires finer granularity.

**Include in prompts:**

```md
# 🛡️ Data Encapsulation and Testing Guidelines (Python)

* ✅ Only test public methods and attributes.
* ❌ Never test `_internal` members directly.
* ✅ If internal logic must be tested, extract it into testable public utility classes.
* ✅ Always import code through public exports—never rely on internal module paths.
* ❌ Avoid mocks. All tests should use real `llvmlite` integration for validation.
```

---

### 🧠 GhostDev Configuration Plan

Sample `.ghostdev.yml` outline:

```yaml
test_command: "just test"
coverage_command: "just coverage"
max_iterations: 10
test_timeout: 45
root_dir: "."

context_rules:
  path_globs:
    - "tests/**/*.py"
    - "py2bin/**/*.py"
  max_lines: 250

prompts:
  fix_generation: |
    Fix failing tests and improve transpilation correctness.
    Follow public API design and encapsulation rules:
    - Do not access `_internal` members directly.
    - Do not use `__double_underscore` methods.
    - Use `llvmlite` directly instead of mocking.
    - All improvements must maintain or improve coverage.
    - Maintain semantic correctness of all transformations.
    - Extract reusable logic into testable utilities when needed.

  error_analysis: |
    Identify reasons for failure by analyzing test results, code structure, and coverage reports.
    Suggest fixes that align with encapsulation policies and project-specific constraints.

policies:
  test_coverage:
    min_coverage: 85
    fail_on_decrease: true

  test_success:
    required_passing: 100

  feature_progress:
    at_least_one_doing_test_must_pass: true
```

---

### 🧪 Testing Enforcement

* Unit tests should never mock internals—test against real LLVM IR execution where possible
* All tests should use `just test` and `py2bin batch ...` to validate success

---

### 🔄 Automation Expectations

GhostDev should:

1. Continuously analyze failures in “doing” tests
2. Generate valid transpilation improvements
3. Adhere to public API and encapsulation rules
4. Commit only when all policy gates are passed
5. Repeat until completion

---

### 📌 Acceptance Criteria

* [ ] `.ghostdev.yml` committed to root
* [ ] Prompts encode encapsulation and public interface strategy
* [ ] Policies reflect all sections in `policies.txt`
* [ ] At least one successful GhostDev iteration validates “doing” tests
* [ ] Resulting commits strictly avoid `_internal` misuse and pass all tests
